// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAla3mXdx3eizgqXJyDYHDV34T3_2bpwic',
    appId: '1:543284488198:web:43f7e2acd8997cbc2f3b87',
    messagingSenderId: '543284488198',
    projectId: 'megatron-f0b07',
    authDomain: 'megatron-f0b07.firebaseapp.com',
    storageBucket: 'megatron-f0b07.firebasestorage.app',
    measurementId: 'G-C79L6RGDSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxEDU5VD4ClcI40soxQzx_BNY--FoMmPE',
    appId: '1:543284488198:android:c903f69cec57ad6c2f3b87',
    messagingSenderId: '543284488198',
    projectId: 'megatron-f0b07',
    storageBucket: 'megatron-f0b07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ZM9R27kIL0GEM1-sOtXYpaoHGNxh9ZY',
    appId: '1:543284488198:ios:93e3717f8b14ea312f3b87',
    messagingSenderId: '543284488198',
    projectId: 'megatron-f0b07',
    storageBucket: 'megatron-f0b07.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ZM9R27kIL0GEM1-sOtXYpaoHGNxh9ZY',
    appId: '1:543284488198:ios:93e3717f8b14ea312f3b87',
    messagingSenderId: '543284488198',
    projectId: 'megatron-f0b07',
    storageBucket: 'megatron-f0b07.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAla3mXdx3eizgqXJyDYHDV34T3_2bpwic',
    appId: '1:543284488198:web:494d5566aedf44ce2f3b87',
    messagingSenderId: '543284488198',
    projectId: 'megatron-f0b07',
    authDomain: 'megatron-f0b07.firebaseapp.com',
    storageBucket: 'megatron-f0b07.firebasestorage.app',
    measurementId: 'G-549TWDXPV8',
  );
}
